name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile-practice --tag dsci310-dockerfile-practice/dockerfile-practice:cowsay_0.5.0
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: push to Docker hub
      run: docker push dsci310-dockerfile-practice/dockerfile-practice:cowsay_0.5.0
